#!/usr/bin/env python3
"""Export OpenAPI 3 + companion TypeScript types for the Next.js cockpit."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

# Avoid side effects from lifespan during import where possible
from app.main import create_app  # noqa: E402

TS_TYPES = r'''
/**
 * TUNTAS API TypeScript types — keep in sync with backend/openapi.yaml
 * Generated by scripts/export_openapi.py (hand-maintained shapes mirrored from Pydantic).
 *
 * Auth (development):
 *   headers: { "X-Demo-Role": "manager", "X-Demo-Actor": "demo-manager" }
 * Production:
 *   headers: { Authorization: `Bearer ${supabaseJwt}` }
 */

export type RunStatus =
  | "created"
  | "running"
  | "awaiting_approval"
  | "approved_processing"
  | "revising"
  | "completed"
  | "rejected"
  | "failed"
  | "needs_policy_recompile"
  | string;

export type OptionKey = "cost" | "balanced" | "coverage" | string;

export interface HealthResponse {
  status: string;
  app: string;
  env: string;
  time: string; // ISO datetime
}

export interface CreateRunRequest {
  request_id?: string | null;
  trigger_path?: string | null;
  trigger_payload?: Record<string, unknown> | null;
  use_synthetic_fallback?: boolean;
}

export interface CreateRunResponse {
  run_id: string;
  thread_id: string;
  request_id: string;
  status: RunStatus;
  employee_count: number;
  synthetic: boolean;
}

export interface ExecuteRunResponse {
  run_id: string;
  status: RunStatus;
  current_node?: string | null;
  message: string;
}

export interface DecisionRequest {
  option_key: OptionKey;
  decision: "approve" | "reject" | "revise";
  rationale: string;
  conditions?: string[];
  acting_manager_id?: string | null;
  return_to_stage?: "learning_architect" | "challenger" | "optimizer" | "secretariat" | null;
  /** Stale guard — pass portfolio_version from cockpit/what-if */
  expected_portfolio_version?: string | null;
}

export interface DecisionResponse {
  run_id: string;
  status: RunStatus;
  decision_id?: string | null;
  message: string;
}

export interface MeResponse {
  subject: string;
  role: string;
  email?: string | null;
  auth_mode: string;
  permissions: string[];
}

export interface ErrorResponse {
  detail: string | Record<string, unknown> | unknown[];
}

export interface RunStatusView {
  run_id: string;
  status: RunStatus;
  current_node?: string | null;
  updated_at: string;
  awaiting_approval: boolean;
  portfolio_version?: string | null;
  error_message?: string | null;
}

/** SSE event names for GET /v1/runs/{run_id}/events/stream */
export type RunRealtimeSseEvent =
  | "connected"
  | "status"
  | "audit"
  | "handoff"
  | "heartbeat";

export interface RunRequestSummary {
  request_id?: string | null;
  source?: string | null;
  synthetic: boolean;
  max_budget_per_employee_myr?: number | null;
  total_budget_myr?: number | null;
  min_operational_coverage_ratio?: number | null;
  training_window_start?: string | null;
  training_window_end?: string | null;
  frameworks: string[];
  employee_count: number;
  portfolio_version?: string | null;
}

/** Full portfolio shape — returned by GET /runs/{id}, /options, /cockpit, /what-if */
export interface PortfolioOptionDetail {
  id: string;
  option_key: OptionKey;
  label: string;
  total_cost_myr: number;
  cost_per_employee_myr: number;
  coverage_score: number;
  risk_reduction_score: number;
  operational_coverage: number;
  hard_constraint_ok: boolean;
  solver_status?: string | null;
  challenger_flags: Record<string, unknown>[];
  metrics: Record<string, unknown>;
  assignments: Record<string, unknown>[];
}

export interface WhatIfRequest {
  max_cost_per_employee_myr?: number | null;
  total_budget_myr?: number | null;
  min_operational_coverage_ratio?: number | null;
  /** false = preview only; true (default) = persist DB + sync LangGraph checkpoint */
  apply?: boolean;
}

export interface WhatIfResponse {
  run_id: string;
  options: PortfolioOptionDetail[];
  applied: boolean;
  checkpoint_synced: boolean;
  portfolio_version?: string | null;
}

export interface RunEvent {
  id: string;
  event_type: string;
  actor_id: string;
  actor_role: string;
  payload: Record<string, unknown>;
  created_at: string;
}

export interface RunListItem {
  id: string;
  request_id: string;
  thread_id: string;
  status: RunStatus;
  current_node?: string | null;
  trigger_schema_version: string;
  selected_option_id?: string | null;
  created_at: string;
  updated_at: string;
  error_message?: string | null;
  employee_count: number;
}

/** GET /v1/runs/{run_id} — options include assignments (same as /options) */
export interface RunDetail {
  id: string;
  request_id: string;
  thread_id: string;
  status: RunStatus;
  current_node?: string | null;
  trigger_schema_version: string;
  employee_count: number;
  selected_option_id?: string | null;
  created_at: string;
  updated_at: string;
  options: PortfolioOptionDetail[];
  latest_events: RunEvent[];
}

export interface AgentHandoffView {
  id: string;
  agent_name: string;
  input_hash: string;
  output_json: Record<string, unknown>; // envelope: schema_version, payload, confidence, ...
  citation_coverage?: number | null;
  latency_ms?: number | null;
  model_name?: string | null;
  created_at: string;
}

export interface TimelineResponse {
  run_id: string;
  items: Array<
    | {
        kind: "handoff";
        id: string;
        at: string;
        agent_name: string;
        latency_ms?: number | null;
        model_name?: string | null;
        citation_coverage?: number | null;
        requires_review: boolean;
        summary: string;
      }
    | {
        kind: "event";
        id: string;
        at: string;
        event_type: string;
        actor_id: string;
        actor_role: string;
        payload: Record<string, unknown>;
      }
  >;
}

export interface EvidenceNodeView {
  id: string;
  node_type: string;
  external_ref: string;
  label: string;
  payload: Record<string, unknown>;
  content_hash?: string | null;
  created_at?: string | null;
}

export interface EvidenceEdgeView {
  id: string;
  from_node_id: string;
  to_node_id: string;
  edge_type: string;
  weight: number;
  payload: Record<string, unknown>;
}

export interface EvidenceGraphResponse {
  run_id: string;
  nodes: EvidenceNodeView[];
  edges: EvidenceEdgeView[];
}

export interface EvidenceLineageResponse {
  root_node_id: string;
  nodes: Record<string, unknown>[];
  edges: Record<string, unknown>[];
}

export interface EmployeeListItem {
  employee_ref: string;
  pseudonym: string;
  role_code?: string | null;
  role_title?: string | null;
  unit?: string | null;
  location?: string | null;
  current_level?: number | null;
  target_level?: number | null;
  availability_pct?: number | null;
  competency_gaps: Record<string, unknown>[];
  readiness: Record<string, unknown>[];
}

export interface EmployeeDetail extends EmployeeListItem {
  assessments: Record<string, unknown>[];
  schedule: Record<string, unknown>[];
  simulation_attempts: Record<string, unknown>[];
}

export interface ScenarioView {
  id: string;
  code: string;
  title: string;
  role_focus: string;
  prompt?: string | null;
  rubric: Record<string, unknown>[];
  created_at?: string | null;
}

export interface TrainingSessionView {
  id: string;
  course_code: string;
  title: string;
  starts_at: string;
  ends_at: string;
  delivery_mode: string;
  location?: string | null;
  capacity: number;
  metadata: Record<string, unknown>;
}

export interface ScheduleAssignmentView {
  id: string;
  employee_ref: string;
  course_code: string;
  cost_myr: number;
  session_id: string;
  session_title?: string | null;
  starts_at?: string | null;
  ends_at?: string | null;
}

export interface AssuranceSnapshotView {
  id: string;
  kirkpatrick: Record<string, unknown>;
  residual_risk: Record<string, unknown>;
  control_coverage: Record<string, unknown>;
  created_at: string;
}

export interface ApprovalDecisionView {
  id: string;
  decision: string;
  conditions: unknown[];
  rationale: string;
  actor_id: string;
  actor_role: string;
  input_hash: string;
  created_at: string;
  option_key: string;
  option_label: string;
}

export interface ArtifactView {
  id: string;
  artifact_type: string;
  filename: string;
  storage_path?: string | null;
  content_type: string;
  sha256: string;
  hmac_signature: string;
  byte_size: number;
  created_at: string;
}

export interface CockpitBundle {
  run: {
    id: string;
    request_id: string;
    thread_id: string;
    status: RunStatus;
    current_node?: string | null;
    trigger_schema_version: string;
    employee_count: number;
    selected_option_id?: string | null;
    created_at: string;
    updated_at: string;
    error_message?: string | null;
    awaiting_approval: boolean;
  };
  request?: RunRequestSummary | null;
  options: PortfolioOptionDetail[];
  handoffs: AgentHandoffView[];
  latest_events: Record<string, unknown>[];
  assurance: AssuranceSnapshotView | null;
  assurance_history: AssuranceSnapshotView[];
  scenarios: Array<{ id: string; code: string; title: string; role_focus: string }>;
  artifacts: ArtifactView[];
  sessions: TrainingSessionView[];
  approval: ApprovalDecisionView | null;
  employee_count: number;
  portfolio_version?: string | null;
}

export interface AdaptiveSessionView {
  session_id: string;
  scenario_id: string;
  run_id: string;
  employee_ref: string;
  status: string;
  difficulty: string;
  turns: Record<string, unknown>[];
  attempt_id?: string | null;
  created_at?: string | null;
  updated_at?: string | null;
  adaptive: boolean;
}

export interface BlastRadiusResponse {
  run_id?: string | null;
  framework_code?: string | null;
  affected_nodes: Record<string, unknown>[];
  affected_employees: string[];
  affected_courses: string[];
  [key: string]: unknown;
}

export interface BlastReopenRequest {
  framework_code: string;
  reason?: string;
}

export interface BlastReopenResponse {
  run_id: string;
  status: RunStatus;
  framework_code: string;
  recompiled_employee_count: number;
  affected_employees: string[];
  langgraph_interrupt_rearmed: boolean;
  options: Record<string, unknown>[];
  message: string;
}

export interface SimulationAttemptRequest {
  employee_ref: string;
  responses: Record<string, unknown>;
}

export interface SimulationAttemptResponse {
  attempt_id: string;
  score: number;
  level_awarded: number;
  evidence_hash: string;
  feedback: Record<string, unknown>;
  assurance_phase?: string | null;
  assurance_refreshed?: boolean | null;
  assurance_error?: string | null;
  residual_risk?: Record<string, unknown> | null;
  session_id?: string | null;
  adaptive?: boolean | null;
  status?: string | null;
  learner_turns?: number | null;
}

export interface AdaptiveSessionStartResponse {
  session_id: string;
  scenario_id: string;
  employee_ref: string;
  status: string;
  difficulty: string;
  turn: Record<string, unknown>;
  adaptive: boolean;
  scoring: string;
}

export interface AdaptiveTurnResponse {
  session_id: string;
  status: string;
  difficulty: string;
  learner_turn: Record<string, unknown>;
  turn: Record<string, unknown>;
  can_finalize: boolean;
  adaptive: boolean;
}

export interface MetricsSummary {
  runs_total: number;
  runs_awaiting_approval: number;
  runs_completed: number;
  hard_constraint_violations: number;
  avg_budget_utilization: number | null;
  citation_coverage_avg: number | null;
  approval_bypass_attempts: number;
  avg_handoff_latency_ms?: number | null;
  artifact_completeness_avg?: number | null;
}

export interface AssuranceRefreshResponse {
  run_id: string;
  phase: string;
  assurance: Record<string, unknown>;
  node_id?: string | null;
}

/**
 * Complete path map — must stay 1:1 with FastAPI routes in openapi.yaml.
 * Regenerate via: python scripts/export_openapi.py
 */
export type ApiPaths = {
  "GET /health": { response: HealthResponse };
  "GET /v1/me": { response: MeResponse };

  "GET /v1/runs": { response: RunListItem[] };
  "POST /v1/runs": { body: CreateRunRequest; response: CreateRunResponse };
  "GET /v1/runs/{run_id}": { response: RunDetail };
  "GET /v1/runs/{run_id}/status": { response: RunStatusView };
  "POST /v1/runs/{run_id}/execute": { response: ExecuteRunResponse };
  "GET /v1/runs/{run_id}/cockpit": { response: CockpitBundle };
  "GET /v1/runs/{run_id}/events": { response: RunEvent[] };
  /** SSE text/event-stream — events: connected | status | audit | handoff | heartbeat */
  "GET /v1/runs/{run_id}/events/stream": {
    query?: {
      demo_role?: string;
      demo_actor?: string;
      access_token?: string;
      heartbeat_seconds?: number;
    };
    response: ReadableStream; // text/event-stream
  };
  "GET /v1/runs/{run_id}/handoffs": { response: AgentHandoffView[] };
  "GET /v1/runs/{run_id}/timeline": { response: TimelineResponse };
  "GET /v1/runs/{run_id}/evidence-graph": { response: EvidenceGraphResponse };
  "GET /v1/runs/{run_id}/employees": { response: EmployeeListItem[] };
  "GET /v1/runs/{run_id}/employees/{employee_ref}": { response: EmployeeDetail };
  "GET /v1/runs/{run_id}/scenarios": { response: ScenarioView[] };
  "GET /v1/runs/{run_id}/sessions": { response: TrainingSessionView[] };
  "GET /v1/runs/{run_id}/assignments": { response: ScheduleAssignmentView[] };
  "GET /v1/runs/{run_id}/assurance": { response: AssuranceSnapshotView[] };
  "POST /v1/runs/{run_id}/assurance/refresh": { response: AssuranceRefreshResponse };
  "GET /v1/runs/{run_id}/approval": { response: ApprovalDecisionView | null };
  "GET /v1/runs/{run_id}/approvals": { response: ApprovalDecisionView[] };
  "GET /v1/runs/{run_id}/options": { response: PortfolioOptionDetail[] };
  "GET /v1/runs/{run_id}/options/{option_key}": { response: PortfolioOptionDetail };
  "POST /v1/runs/{run_id}/what-if": { body: WhatIfRequest; response: WhatIfResponse };
  "POST /v1/runs/{run_id}/decision": {
    body: DecisionRequest;
    headers?: { "Idempotency-Key"?: string };
    response: DecisionResponse;
  };
  "POST /v1/runs/{run_id}/resume": {
    body: DecisionRequest;
    headers?: { "Idempotency-Key"?: string };
    response: DecisionResponse;
  };
  "GET /v1/runs/{run_id}/artifacts": { response: ArtifactView[] };
  "GET /v1/runs/{run_id}/blast-radius": { response: BlastRadiusResponse };
  "POST /v1/runs/{run_id}/blast-radius/reopen": {
    body: BlastReopenRequest;
    response: BlastReopenResponse;
  };

  "GET /v1/artifacts/{artifact_id}": { response: Blob }; // FileResponse download
  "GET /v1/evidence/{node_id}/lineage": { response: EvidenceLineageResponse };
  "GET /v1/metrics/summary": { response: MetricsSummary };

  "POST /v1/simulations/{scenario_id}/attempts": {
    body: SimulationAttemptRequest;
    response: SimulationAttemptResponse;
  };
  "POST /v1/simulations/{scenario_id}/sessions": {
    body: { employee_ref: string };
    response: AdaptiveSessionStartResponse;
  };
  "GET /v1/simulations/{scenario_id}/sessions": { response: AdaptiveSessionView[] };
  "GET /v1/simulations/sessions/{session_id}": { response: AdaptiveSessionView };
  "POST /v1/simulations/sessions/{session_id}/turns": {
    body: { learner_action: string; actions?: string[] };
    response: AdaptiveTurnResponse;
  };
  "POST /v1/simulations/sessions/{session_id}/finalize": {
    response: SimulationAttemptResponse;
  };
  "POST /v1/simulations/sessions/{session_id}/abandon": {
    response: AdaptiveSessionView;
  };
};
'''


def main() -> None:
    app = create_app()
    spec = app.openapi()
    spec["info"]["title"] = "TUNTAS API"
    spec["info"]["description"] = (
        "Traceable Upskilling & Normative Training Assurance System.\n\n"
        "Frontend first-paint: `GET /v1/runs/{run_id}/cockpit` → `CockpitBundle`.\n"
        "Dev auth: headers `X-Demo-Role` + optional `X-Demo-Actor` when DEMO_AUTH_BYPASS=true.\n"
        "TypeScript types: see `openapi.types.ts` (x-typescript-types embedded below)."
    )
    spec["info"]["x-typescript-types"] = TS_TYPES
    spec["servers"] = [
        {"url": "http://localhost:8001", "description": "Local TUNTAS API (TrustLoop uses 8000)"},
    ]
    components = spec.setdefault("components", {})
    components["securitySchemes"] = {
        "BearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT",
            "description": "Supabase access token (Authorization: Bearer …)",
        },
        "DemoRole": {
            "type": "apiKey",
            "in": "header",
            "name": "X-Demo-Role",
            "description": "Dev-only role when DEMO_AUTH_BYPASS=true (viewer|analyst|manager|compliance|admin)",
        },
        "DemoActor": {
            "type": "apiKey",
            "in": "header",
            "name": "X-Demo-Actor",
            "description": "Optional demo actor id paired with X-Demo-Role",
        },
        "McpToken": {
            "type": "apiKey",
            "in": "header",
            "name": "X-MCP-Token",
            "description": "WorkBuddy MCP service token",
        },
    }
    # Document accepted auth modes (actual enforcement is per-route via Depends)
    spec["security"] = [
        {"BearerAuth": []},
        {"DemoRole": [], "DemoActor": []},
        {"McpToken": []},
    ]
    # Ensure global error schema is present for codegen consumers
    schemas = components.setdefault("schemas", {})
    schemas.setdefault(
        "ErrorResponse",
        {
            "title": "ErrorResponse",
            "type": "object",
            "properties": {
                "detail": {
                    "anyOf": [
                        {"type": "string"},
                        {"type": "object"},
                        {"type": "array", "items": {}},
                    ]
                }
            },
            "required": ["detail"],
        },
    )

    out_yaml = ROOT / "openapi.yaml"
    out_json = ROOT / "openapi.json"
    out_ts = ROOT / "openapi.types.ts"
    # also copy-friendly for frontend/
    fe_dir = ROOT.parent / "frontend"
    fe_dir.mkdir(parents=True, exist_ok=True)

    try:
        import yaml  # type: ignore

        out_yaml.write_text(
            yaml.safe_dump(spec, sort_keys=False, allow_unicode=True),
            encoding="utf-8",
        )
    except Exception:
        # minimal YAML-ish fallback via json
        out_yaml.write_text(json.dumps(spec, indent=2, default=str), encoding="utf-8")

    out_json.write_text(json.dumps(spec, indent=2, default=str), encoding="utf-8")
    out_ts.write_text(TS_TYPES.lstrip() + "\n", encoding="utf-8")
    (fe_dir / "openapi.yaml").write_text(out_yaml.read_text(encoding="utf-8"), encoding="utf-8")
    (fe_dir / "openapi.types.ts").write_text(out_ts.read_text(encoding="utf-8"), encoding="utf-8")

    paths = sorted(spec.get("paths", {}).keys())
    print(f"Wrote {out_yaml}")
    print(f"Wrote {out_ts}")
    print(f"Wrote {fe_dir / 'openapi.yaml'}")
    print(f"paths={len(paths)}")
    for p in paths:
        print(" ", p)


if __name__ == "__main__":
    main()
